### PR TITLE
Make ClickHouseBinaryFormatReader also extend Iterator

### LINKED ISSUE #1963: Why not `ClickHouseBinaryFormatReader` extends `Iterator` or `Stream` interface ?
### Describe your feedback

I think [ClickHouseBinaryFormatReader](https://github.com/ClickHouse/clickhouse-java/blob/main/client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java) should also extends `Iterator` or `Stream` interface, that will make handle large result set very easy to use Java Stream API.

### Code example

Maybe this will be a use case:

```java
QueryResponse response = this.client.query("select * from mytable").get();
ClickHouseBinaryFormatReader reader = client.newBinaryFormatReader(response);

// if ClickHouseBinaryFormatReader extends Stream, we can use
reader.map(....).filter(...)

// if ClickHouseBinaryFormatReader extends Iterator, we can use
StreamSupport.stream(Spliterators.spliteratorUnknownSize(reader, 0), false).map(...).filter(...)
```

Thanks.

### PR DESCRIPTION
**Pull request by abcfy2**
Fix #1963

## Summary

Make ClickHouseBinaryFormatReader also extend Iterator interface.

### CODE REVIEW

**Comment by chernser** [comment]
Good day, @abcfy2 ! 
Thank you for the contribution! 
However I do not plan to make reader as iterator. There is `com.clickhouse.client.api.Client#queryRecords(java.lang.String)` designed to be iterable reader. Would it work for your usecase? 

Thanks!

**Comment by abcfy2** [comment]
I think it also makes sense to make ClickHouseBinaryFormatReader extend `Iterator` interface. Because `ClickHouseBinaryFormatReader` supports some methods like `getBoolean, getBigInteger` and so on.

**Comment by abcfy2** [comment]
@chernser By the way, when will the new version release? I need the `queryRecords with prepared statement` feature.

I find `0.7.1` does not support this yet, but the code has been already added in the main branch.

**Comment by chernser** [comment]
@abcfy2 the new version is planned by end of the December.
The prepared statements are done already in Nightly build, I think. (here is how to use nightly build https://gist.github.com/chernser/b4eacfde70093847449e3aef8e51ae8e) 

Are you looking for this method, right?:
```
public CompletableFuture<Records> queryRecords(String sqlQuery, Map<String, Object> params, QuerySettings settings)
```

**Comment by abcfy2** [comment]
> @abcfy2 the new version is planned by end of the December. The prepared statements are done already in Nightly build, I think. (here is how to use nightly build https://gist.github.com/chernser/b4eacfde70093847449e3aef8e51ae8e)
> 
> Are you looking for this method, right?:
> 
> ```
> public CompletableFuture<Records> queryRecords(String sqlQuery, Map<String, Object> params, QuerySettings settings)
> ```

Yes. That's what I need. Current it's not in `0.7.1`. Waiting for `0.7.2`

**Pull request closed without merging**
