### PR TITLE
Drop gRPC client

### LINKED ISSUE #1399: Drop clickhouse-grpc-client
gRPC has been available as an experimental feature in ClickHouse for a while, but it lacks active maintenance, likely due to its limited usage. In this repository, the `clickhouse-grpc-client` was primarily developed to test interfaces in `clickhouse-client`. However, this addition introduces a multitude of dependencies into a relatively small library, resulting in intermittent build failures during continuous integration. Consequently, it is not recommended for production usage due to issues such as inadequate lz4 support and excessive server memory consumption.

Speaking from my personal experience at a company that follows the "use it or lose it" philosophy, I strongly advise removing the `clickhouse-grpc-client`. This action would not only resolve the CI build failures and eliminate unnecessary dependencies but also eliminate any confusion for users.

Lastly, I would like to mention that Apache Arrow Flight might be a more viable alternative. We can revisit this topic when ClickHouse/ClickHouse#7554 is implemented.

### PR DESCRIPTION
**Pull request by zhicwu**
## Summary
Closes #1399

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by zhicwu** [comment]
Hi @mzitnik, please review this pull request at your earliest convenience. I will be submitting a few more pull requests for updating dependencies, addressing bugs, and merging pending pull requests.

**Comment by mzitnik** [comment]
@zhicwu did you decide to drop gRPC ?

**Comment by zhicwu** [comment]
Yes, I see no benefit of keeping this but troubles(e.g. never production ready, CI failure time from time, and extra dependencies etc.). As I mentioned in the linked issue, Apache Arrow Flight is probably a better choice, and hopefully it will be supported in the future.

**Comment by chernser** [comment]
Replaced with https://github.com/ClickHouse/clickhouse-java/pull/1844

**Pull request closed without merging**
