### PR TITLE
support custom socket factory

### PR DESCRIPTION
**Pull request by zhicwu**
## Summary
Support custom socket factory as requested in #1391.

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by mzitnik** [comment]
@zhicwu do we have associated issue for this PR

**Comment by mzitnik** [comment]
@zhicwu can you provide a code sample so we could add it to documentation

**Comment by zhicwu** [comment]
> @zhicwu can you provide a complete code sample so we could add it to documentation

There's test([example](https://github.com/ClickHouse/clickhouse-java/blob/2f0aa9f9b98cae23083aa1b53542d242d9eaa601/clickhouse-http-client/src/test/java/com/clickhouse/client/http/ApacheHttpConnectionImplTest.java#L30-L54)) as well as [default implementation](https://github.com/ClickHouse/clickhouse-java/blob/2f0aa9f9b98cae23083aa1b53542d242d9eaa601/clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java#L273-L296). Do we still need complete code sample? I didn't see that happening in the server repo :)

Anyway, this was requested by @mayankvadariya, so let's wait for his comments before merging the PR.

**Comment by zhicwu** [comment]
@mzitnik, can we merge this PR to close the issue?

**Review by mzitnik — APPROVED** [review]

**Comment by mayankvadariya** [comment]
Thank you @zhicwu for this effort. It slipped as I had been busy lately.

**Comment by zhicwu** [comment]
> Thank you @zhicwu for this effort. It slipped as I had been busy lately.

No problem. Let us know if it fits your need.

**Comment by mayankvadariya** [comment]
Yes, I tested the changes locally. 🙌  Please let me know when can we release these changes.

**Pull request merged**
