### PR TITLE
optimize find column index

### PR DESCRIPTION
**Pull request by Okapist**
## Summary

ClickhouseResultSet look for column index on each row. It use expensive equalsIgnoreCase method.
I added index cache for it.

### CODE REVIEW

**Comment by Okapist** [comment]
Collections.synchronizedMap(new HashMap<>()) may be replaced with ConcurrentHashMap if not need to support old jdk versions.

**Comment by zhicwu** [comment]
Thank you @Okapist for the pull request and sorry for the late reply.

Can we create the HashMap only when needed(e.g. first time calling findColumnIndex)? Besides, when instantiate the cache, can we specify the load factor since we know the maximum number of columns?

**Comment by Okapist** [comment]
> Can we create the HashMap only when needed(e.g. first time calling findColumnIndex)? Besides, when instantiate the cache, can we specify the load factor since we know the maximum number of columns?

Good idea. Pull request updated.

**Comment by zhicwu** [comment]
Thanks @Okapist. Will merge this one after fixing build failure.

**Pull request closed without merging**
